### ISSUE TITLE
B9 Procedural Wings with TU changes P-wing Textures After Reverting to Launch when BDA is Installed

### ISSUE THREAD

**Issue by VostokV5** [shadowmage45/TexturesUnlimited#106]
[Player.log](https://github.com/shadowmage45/TexturesUnlimited/files/9132554/Player.log)

KSP 1.12.3 Windows 64bit

**Problem:** 
- B9 Procedural Wings with Textures Unlimited changes the textures of the leading edge, trailing edge, and section of the P-wing when  BDA is installed
- Also works with the other B9 P-wings (Control surface and All-moving); Same thing, every section except the actual surface goes back to its original texture.

 
**Mods Installed:**
- B9 Aerospace Procedural Wings Fork 0.43.0.11
- BDArmory for Runway Project 1.4.18.4
- Module Manager 4.2.2
- Textures Unlimited 1.5.10.25

**Reproduction Steps:**
1. Make a craft with B9 Procedural Wings
2. Recolor the main parts of each section of the P-wing
3. Launch 
4. Revert to launch and then the bug should appear

[VIDEO OF REPRODUCTION](https://youtu.be/6a2Na50aeIs)

**Comment by BrettRyland** [comment]
@shadowmage45 This is caused by part module index mismatches (or re-ordering of the modules in the craft file) that aren't triggering all the "enabling TSMD.." lines (see the linked issue), e.g., this simple craft file [Untitled Space Craft.craft](https://github.com/shadowmage45/TexturesUnlimited/files/9134581/Untitled.Space.Craft.craft.txt) has the first two `KSPTextureSwitch` modules moved to after the latter two, which causes this
![Screenshot_20220718_205225](https://user-images.githubusercontent.com/18440126/179585695-6e2de1fe-e66f-432f-8adc-131c877023d5.png)
 Any mod or MM patch that dynamically adds modules to parts is going to cause similar behaviour.

**Comment by VostokV5** [comment]
Closing this since it is now fixed with KSPCommunityFixes installed. Thanks for the help!
