### ISSUE TITLE
KSPTextureSwitch Value Bleeding

### ISSUE THREAD

**Issue by Electrocutor** [shadowmage45/TexturesUnlimited#35]
When switching between TextureSets, values not specified do not return to default values.

Scenario:
KSP_TEXTURE_SET
{
	name = Metal
	title = Metal
	recolorable = false

	TEXTURE
	{
		shader = SSTU/PBR/Metallic

		PROPERTY
		{
			name = _Metal
			float = 0.75
		}
		PROPERTY
		{
			name = _Smoothness
			float = 0.75
		}
	}
}
KSP_TEXTURE_SET
{
	name = RedMetal
	title = RedMetal
	recolorable = false

	TEXTURE
	{
		shader = SSTU/PBR/Metallic

		PROPERTY
		{
			name = _Color
			color = 1.0,0,0
		}
		PROPERTY
		{
			name = _Metal
			float = 0.75
		}
		PROPERTY
		{
			name = _Smoothness
			float = 0.75
		}
	}
}

However, also remember that if there are multiple instances of KSPTextureSwitch, they may be cumulative. For example, one instance to set _Color and one to set _Metal and _Smoothness.

**Comment by shadowmage45** [comment]
Bit of info on the subject:

https://forum.unity.com/threads/how-to-initialize-reset-and-purge-shader-material-variables.350529/

**Comment by shadowmage45** [comment]
Looking into this -- it is not really something that I can solve.  Unity does not give access to the 'default' parameter values from scripting code.  The parameter values will simply need to be specified in the configs.

The only potential solution would be to instead of re-using the existing material, re-create the material every time the texture set was changed.  This would re-set the parameters to the default as defined in the shader source.  That is the only option, but it seems like a terrible one to me from a GC perspective.

(Far simpler to just define the parameters in the config files; if you want to use the parameters, you must define values for them)
