### ISSUE TITLE
_Metal vs _Metallic

### ISSUE THREAD

**Issue by Electrocutor** [shadowmage45/TexturesUnlimited#36]
Whether to use _Metal or _Metallic has been switching back and forth depending on version and which shader you use. Could you please standardize it?

For example, in 1.0.0.5, the stock shader used _Metal, but in 1.0.0.6 it now uses _Metallic again, like it was before.

**Comment by shadowmage45** [comment]
Gah, I hate Unity (and the BS I have to do to use it).  Really hate Unity.  (really, this problem **simply shouldn't exist because _Metallic should just work** ... but Unity... what a stupid POS game engine)

It **should** be _Metal.  But Unity loves mangling things when they are put into a repository (it likes to overwrite files with what it _thinks_ is correct; and apparently I missed one of its changes).

Will make sure it is _Metal again in the next (and future) releases.

**Comment by Electrocutor** [comment]
Some of the others shaders had never been changed to _Metal at all, like the Transparency and Solar shaders. You may want to take the moment to go over them all.

Alternatively, now that you've figured out Keywords, if you allow them to also be disabled, you could just mash this all down into one or two shaders that you turn things on and off, since most of the code is duplicated anyway.

**Comment by shadowmage45** [comment]
Just caught and fixed the transparent shader.  Will also use _Metal for the metallic value multiplier in future releases.  Don't think I'm using that property in any of the other shaders -- just the two stock ones, and the PBR/Metallic variant.

Keywords -- likely will transition to those during the KSP 1.4 update.  As it will require adjusting thousands of texture set configs in SSTU (not joking, there are a lot of them), I would prefer to schedule it for when I'll already be doing 'game breaking' work and rewriting the configs anyway.  (even if I were to do the keyword changes -today-, I wouldn't be able to release them until SSTU was fixed for the changes, which might take a couple weeks)
